// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Component: typeof import('./src/components/vue-number-format/component.vue')['default']
    CustomerForm: typeof import('./src/components/forms/CustomerForm.vue')['default']
    DetailList: typeof import('./src/components/forms/stock/DetailList.vue')['default']
    DropdownNonBorder: typeof import('./src/components/DropdownNonBorder.vue')['default']
    FycDropdown: typeof import('./src/components/FycDropdown.vue')['default']
    ProductForm: typeof import('./src/components/forms/ProductForm.vue')['default']
    SalesForm: typeof import('./src/components/forms/SalesForm.vue')['default']
    StockForm: typeof import('./src/components/forms/stock/StockForm.vue')['default']
    SupplierForm: typeof import('./src/components/forms/SupplierForm.vue')['default']
    TheNavbar: typeof import('./src/components/layouts/TheNavbar.vue')['default']
    TheSidebar: typeof import('./src/components/layouts/TheSidebar.vue')['default']
    TheSidebarMenuHeader: typeof import('./src/components/layouts/TheSidebarMenuHeader.vue')['default']
    TheSidebarMenuItem: typeof import('./src/components/layouts/TheSidebarMenuItem.vue')['default']
    TheSidebarSubMenuHeader: typeof import('./src/components/layouts/TheSidebarSubMenuHeader.vue')['default']
    TheSidebarSubMenuItem: typeof import('./src/components/layouts/TheSidebarSubMenuItem.vue')['default']
    TwButton: typeof import('./src/components/TwButton.vue')['default']
    TwCodePreviewEditor: typeof import('./src/components/TwCodePreviewEditor.vue')['default']
    TwDropdown: typeof import('./src/components/TwDropdown.vue')['default']
    TwIcon: typeof import('./src/components/TwIcon.vue')['default']
    TwTooltip: typeof import('./src/components/TwTooltip.vue')['default']
    UnitForm: typeof import('./src/components/forms/UnitForm.vue')['default']
    UnitList: typeof import('./src/components/forms/UnitList.vue')['default']
  }
}

export { }
