#! /bin/sh
# copy thi file to /etc/init.d/

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/home/fyc/projects/yoga-fastapi-postgres/run-service.sh
PIDFILE=/var/run/scriptname.pid

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
     log_daemon_msg "Starting feedparser"
     start_daemon -p $PIDFILE $DAEMON
     log_end_msg $?
   ;;
  stop)
     log_daemon_msg "Stopping feedparser"
     killproc -p $PIDFILE $DAEMON
     PID=`ps x |grep python | head -1 | awk '{print $1}'`
     kill -9 $PID       
     log_end_msg $?
     PID=`ps x |grep python | head -1 | awk '{print $1}'`
     kill -9 $PID       
     log_end_msg $?
     PID=`ps x |grep python | head -1 | awk '{print $1}'`
     kill -9 $PID       
     log_end_msg $?
   ;;
  force-reload|restart)
     $0 stop
     $0 start
   ;;
  status)
     status_of_proc -p $PIDFILE $DAEMON test && exit 0 || exit $?
   ;;
 *)
   echo "Usage: /etc/init.d/test {start|stop|restart|force-reload|status}"
   exit 1
  ;;
esac

exit 0